import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header.jsx'
import Footer from './components/Footer'
import Sidemenu from './components/Sidemenu'
import Form from './components/Form'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ShowboxMoviesClone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        <Form/>
        <Sidemenu/>
      </body>
    </html>
  )
}
